server:
  port: 8001
swagger:
  enable: true

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.example.mybatis.model