// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jpush.proto

package com.example.common.mq.jpush;

public final class JPushMessage {
  private JPushMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code jpush.TopicJpush}
   */
  public enum TopicJpush
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>eTopicJpush = 0;</code>
     */
    eTopicJpush(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>eTopicJpush = 0;</code>
     */
    public static final int eTopicJpush_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static TopicJpush valueOf(int value) {
      return forNumber(value);
    }

    public static TopicJpush forNumber(int value) {
      switch (value) {
        case 0: return eTopicJpush;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TopicJpush>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TopicJpush> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TopicJpush>() {
            public TopicJpush findValueByNumber(int number) {
              return TopicJpush.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return JPushMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final TopicJpush[] VALUES = values();

    public static TopicJpush valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TopicJpush(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jpush.TopicJpush)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpush.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appkey = 1;</code>
     */
    String getAppkey();
    /**
     * <code>string appkey = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <code>string secret = 2;</code>
     */
    String getSecret();
    /**
     * <code>string secret = 2;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>string alert = 3;</code>
     */
    String getAlert();
    /**
     * <code>string alert = 3;</code>
     */
    com.google.protobuf.ByteString
        getAlertBytes();

    /**
     * <code>repeated string tags = 4;</code>
     */
    java.util.List<String>
        getTagsList();
    /**
     * <code>repeated string tags = 4;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated string tags = 4;</code>
     */
    String getTags(int index);
    /**
     * <code>repeated string tags = 4;</code>
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);

    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    java.util.List<String>
        getTagsAndList();
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    int getTagsAndCount();
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    String getTagsAnd(int index);
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    com.google.protobuf.ByteString
        getTagsAndBytes(int index);

    /**
     * <code>repeated string alias = 6;</code>
     */
    java.util.List<String>
        getAliasList();
    /**
     * <code>repeated string alias = 6;</code>
     */
    int getAliasCount();
    /**
     * <code>repeated string alias = 6;</code>
     */
    String getAlias(int index);
    /**
     * <code>repeated string alias = 6;</code>
     */
    com.google.protobuf.ByteString
        getAliasBytes(int index);

    /**
     * <code>string title = 7;</code>
     */
    String getTitle();
    /**
     * <code>string title = 7;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string extra = 8;</code>
     */
    String getExtra();
    /**
     * <code>string extra = 8;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();
  }
  /**
   * Protobuf type {@code jpush.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpush.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      appkey_ = "";
      secret_ = "";
      alert_ = "";
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      tagsAnd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      alias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      title_ = "";
      extra_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              appkey_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              secret_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              alert_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              tags_.add(s);
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                tagsAnd_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              tagsAnd_.add(s);
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                alias_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              alias_.add(s);
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tags_ = tags_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          tagsAnd_ = tagsAnd_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          alias_ = alias_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JPushMessage.internal_static_jpush_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JPushMessage.internal_static_jpush_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static final int APPKEY_FIELD_NUMBER = 1;
    private volatile Object appkey_;
    /**
     * <code>string appkey = 1;</code>
     */
    public String getAppkey() {
      Object ref = appkey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appkey_ = s;
        return s;
      }
    }
    /**
     * <code>string appkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      Object ref = appkey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECRET_FIELD_NUMBER = 2;
    private volatile Object secret_;
    /**
     * <code>string secret = 2;</code>
     */
    public String getSecret() {
      Object ref = secret_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      }
    }
    /**
     * <code>string secret = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALERT_FIELD_NUMBER = 3;
    private volatile Object alert_;
    /**
     * <code>string alert = 3;</code>
     */
    public String getAlert() {
      Object ref = alert_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        alert_ = s;
        return s;
      }
    }
    /**
     * <code>string alert = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAlertBytes() {
      Object ref = alert_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        alert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList tags_;
    /**
     * <code>repeated string tags = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated string tags = 4;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 4;</code>
     */
    public String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    public static final int TAGSAND_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList tagsAnd_;
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagsAndList() {
      return tagsAnd_;
    }
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    public int getTagsAndCount() {
      return tagsAnd_.size();
    }
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    public String getTagsAnd(int index) {
      return tagsAnd_.get(index);
    }
    /**
     * <code>repeated string tagsAnd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTagsAndBytes(int index) {
      return tagsAnd_.getByteString(index);
    }

    public static final int ALIAS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList alias_;
    /**
     * <code>repeated string alias = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAliasList() {
      return alias_;
    }
    /**
     * <code>repeated string alias = 6;</code>
     */
    public int getAliasCount() {
      return alias_.size();
    }
    /**
     * <code>repeated string alias = 6;</code>
     */
    public String getAlias(int index) {
      return alias_.get(index);
    }
    /**
     * <code>repeated string alias = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAliasBytes(int index) {
      return alias_.getByteString(index);
    }

    public static final int TITLE_FIELD_NUMBER = 7;
    private volatile Object title_;
    /**
     * <code>string title = 7;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 8;
    private volatile Object extra_;
    /**
     * <code>string extra = 8;</code>
     */
    public String getExtra() {
      Object ref = extra_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 8;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppkeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appkey_);
      }
      if (!getSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secret_);
      }
      if (!getAlertBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, alert_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tags_.getRaw(i));
      }
      for (int i = 0; i < tagsAnd_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tagsAnd_.getRaw(i));
      }
      for (int i = 0; i < alias_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, alias_.getRaw(i));
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, title_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, extra_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppkeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appkey_);
      }
      if (!getSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secret_);
      }
      if (!getAlertBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, alert_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += computeStringSizeNoTag(tags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tagsAnd_.size(); i++) {
          dataSize += computeStringSizeNoTag(tagsAnd_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsAndList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < alias_.size(); i++) {
          dataSize += computeStringSizeNoTag(alias_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAliasList().size();
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, title_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, extra_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (!getAppkey()
          .equals(other.getAppkey())) return false;
      if (!getSecret()
          .equals(other.getSecret())) return false;
      if (!getAlert()
          .equals(other.getAlert())) return false;
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!getTagsAndList()
          .equals(other.getTagsAndList())) return false;
      if (!getAliasList()
          .equals(other.getAliasList())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppkey().hashCode();
      hash = (37 * hash) + SECRET_FIELD_NUMBER;
      hash = (53 * hash) + getSecret().hashCode();
      hash = (37 * hash) + ALERT_FIELD_NUMBER;
      hash = (53 * hash) + getAlert().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      if (getTagsAndCount() > 0) {
        hash = (37 * hash) + TAGSAND_FIELD_NUMBER;
        hash = (53 * hash) + getTagsAndList().hashCode();
      }
      if (getAliasCount() > 0) {
        hash = (37 * hash) + ALIAS_FIELD_NUMBER;
        hash = (53 * hash) + getAliasList().hashCode();
      }
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpush.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpush.Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JPushMessage.internal_static_jpush_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JPushMessage.internal_static_jpush_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using jpush.JPushMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        appkey_ = "";

        secret_ = "";

        alert_ = "";

        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        tagsAnd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        alias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";

        extra_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JPushMessage.internal_static_jpush_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        result.appkey_ = appkey_;
        result.secret_ = secret_;
        result.alert_ = alert_;
        if (((bitField0_ & 0x00000001) != 0)) {
          tags_ = tags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tags_ = tags_;
        if (((bitField0_ & 0x00000002) != 0)) {
          tagsAnd_ = tagsAnd_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tagsAnd_ = tagsAnd_;
        if (((bitField0_ & 0x00000004) != 0)) {
          alias_ = alias_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.alias_ = alias_;
        result.title_ = title_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (!other.getAppkey().isEmpty()) {
          appkey_ = other.appkey_;
          onChanged();
        }
        if (!other.getSecret().isEmpty()) {
          secret_ = other.secret_;
          onChanged();
        }
        if (!other.getAlert().isEmpty()) {
          alert_ = other.alert_;
          onChanged();
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (!other.tagsAnd_.isEmpty()) {
          if (tagsAnd_.isEmpty()) {
            tagsAnd_ = other.tagsAnd_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTagsAndIsMutable();
            tagsAnd_.addAll(other.tagsAnd_);
          }
          onChanged();
        }
        if (!other.alias_.isEmpty()) {
          if (alias_.isEmpty()) {
            alias_ = other.alias_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAliasIsMutable();
            alias_.addAll(other.alias_);
          }
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object appkey_ = "";
      /**
       * <code>string appkey = 1;</code>
       */
      public String getAppkey() {
        Object ref = appkey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appkey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        Object ref = appkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       */
      public Builder setAppkey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        appkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       */
      public Builder clearAppkey() {

        appkey_ = getDefaultInstance().getAppkey();
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        appkey_ = value;
        onChanged();
        return this;
      }

      private Object secret_ = "";
      /**
       * <code>string secret = 2;</code>
       */
      public String getSecret() {
        Object ref = secret_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          secret_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string secret = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secret = 2;</code>
       */
      public Builder setSecret(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 2;</code>
       */
      public Builder clearSecret() {

        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>string secret = 2;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        secret_ = value;
        onChanged();
        return this;
      }

      private Object alert_ = "";
      /**
       * <code>string alert = 3;</code>
       */
      public String getAlert() {
        Object ref = alert_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          alert_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string alert = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAlertBytes() {
        Object ref = alert_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          alert_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alert = 3;</code>
       */
      public Builder setAlert(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        alert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string alert = 3;</code>
       */
      public Builder clearAlert() {

        alert_ = getDefaultInstance().getAlert();
        onChanged();
        return this;
      }
      /**
       * <code>string alert = 3;</code>
       */
      public Builder setAlertBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        alert_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTagsList() {
        return tags_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public Builder setTags(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public Builder addTags(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public Builder addAllTags(
          Iterable<String> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public Builder clearTags() {
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 4;</code>
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList tagsAnd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsAndIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          tagsAnd_ = new com.google.protobuf.LazyStringArrayList(tagsAnd_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTagsAndList() {
        return tagsAnd_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public int getTagsAndCount() {
        return tagsAnd_.size();
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public String getTagsAnd(int index) {
        return tagsAnd_.get(index);
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTagsAndBytes(int index) {
        return tagsAnd_.getByteString(index);
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public Builder setTagsAnd(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsAndIsMutable();
        tagsAnd_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public Builder addTagsAnd(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsAndIsMutable();
        tagsAnd_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public Builder addAllTagsAnd(
          Iterable<String> values) {
        ensureTagsAndIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tagsAnd_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public Builder clearTagsAnd() {
        tagsAnd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tagsAnd = 5;</code>
       */
      public Builder addTagsAndBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTagsAndIsMutable();
        tagsAnd_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList alias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAliasIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          alias_ = new com.google.protobuf.LazyStringArrayList(alias_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAliasList() {
        return alias_.getUnmodifiableView();
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public int getAliasCount() {
        return alias_.size();
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public String getAlias(int index) {
        return alias_.get(index);
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAliasBytes(int index) {
        return alias_.getByteString(index);
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public Builder setAlias(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasIsMutable();
        alias_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public Builder addAlias(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasIsMutable();
        alias_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public Builder addAllAlias(
          Iterable<String> values) {
        ensureAliasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alias_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public Builder clearAlias() {
        alias_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string alias = 6;</code>
       */
      public Builder addAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAliasIsMutable();
        alias_.add(value);
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 7;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 7;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 7;</code>
       */
      public Builder clearTitle() {

        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 7;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        title_ = value;
        onChanged();
        return this;
      }

      private Object extra_ = "";
      /**
       * <code>string extra = 8;</code>
       */
      public String getExtra() {
        Object ref = extra_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string extra = 8;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 8;</code>
       */
      public Builder setExtra(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 8;</code>
       */
      public Builder clearExtra() {

        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 8;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        extra_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jpush.Message)
    }

    // @@protoc_insertion_point(class_scope:jpush.Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessagePackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpush.MessagePackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageType = 1;</code>
     */
    int getMessageType();
  }
  /**
   * Protobuf type {@code jpush.MessagePackage}
   */
  public  static final class MessagePackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpush.MessagePackage)
      MessagePackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePackage.newBuilder() to construct.
    private MessagePackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePackage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessagePackage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessagePackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              messageType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JPushMessage.internal_static_jpush_MessagePackage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JPushMessage.internal_static_jpush_MessagePackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessagePackage.class, Builder.class);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>int32 messageType = 1;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != 0) {
        output.writeInt32(1, messageType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessagePackage)) {
        return super.equals(obj);
      }
      MessagePackage other = (MessagePackage) obj;

      if (getMessageType()
          != other.getMessageType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessagePackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessagePackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessagePackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagePackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessagePackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessagePackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessagePackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessagePackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpush.MessagePackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpush.MessagePackage)
        MessagePackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JPushMessage.internal_static_jpush_MessagePackage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JPushMessage.internal_static_jpush_MessagePackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessagePackage.class, Builder.class);
      }

      // Construct using jpush.JPushMessage.MessagePackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JPushMessage.internal_static_jpush_MessagePackage_descriptor;
      }

      @Override
      public MessagePackage getDefaultInstanceForType() {
        return MessagePackage.getDefaultInstance();
      }

      @Override
      public MessagePackage build() {
        MessagePackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessagePackage buildPartial() {
        MessagePackage result = new MessagePackage(this);
        result.messageType_ = messageType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessagePackage) {
          return mergeFrom((MessagePackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessagePackage other) {
        if (other == MessagePackage.getDefaultInstance()) return this;
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessagePackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessagePackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageType_ ;
      /**
       * <code>int32 messageType = 1;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>int32 messageType = 1;</code>
       */
      public Builder setMessageType(int value) {

        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageType = 1;</code>
       */
      public Builder clearMessageType() {

        messageType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jpush.MessagePackage)
    }

    // @@protoc_insertion_point(class_scope:jpush.MessagePackage)
    private static final MessagePackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessagePackage();
    }

    public static MessagePackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePackage>
        PARSER = new com.google.protobuf.AbstractParser<MessagePackage>() {
      @Override
      public MessagePackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagePackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessagePackage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessagePackage> getParserForType() {
      return PARSER;
    }

    @Override
    public MessagePackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpush_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpush_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpush_MessagePackage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpush_MessagePackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013jpush.proto\022\005jpush\"\204\001\n\007Message\022\016\n\006appk" +
      "ey\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\022\r\n\005alert\030\003 \001(\t\022" +
      "\014\n\004tags\030\004 \003(\t\022\017\n\007tagsAnd\030\005 \003(\t\022\r\n\005alias\030" +
      "\006 \003(\t\022\r\n\005title\030\007 \001(\t\022\r\n\005extra\030\010 \001(\t\"%\n\016M" +
      "essagePackage\022\023\n\013messageType\030\001 \001(\005*\035\n\nTo" +
      "picJpush\022\017\n\013eTopicJpush\020\000B\025\n\005jpushB\014JPus" +
      "hMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jpush_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jpush_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpush_Message_descriptor,
        new String[] { "Appkey", "Secret", "Alert", "Tags", "TagsAnd", "Alias", "Title", "Extra", });
    internal_static_jpush_MessagePackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jpush_MessagePackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpush_MessagePackage_descriptor,
        new String[] { "MessageType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
