server:
  port: 8080

swagger:
  enable: true


spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/localtest
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true